import { Playfair_Display } from 'next/font/google'
import './globals.css'

// Initialize the font
const playfair = Playfair_Display({ 
  subsets: ['latin'],
  variable: '--font-playfair' // Custom variable for Tailwind
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.variable}>
        {children}
      </body>
    </html>
  )
}